name: ğŸ”‹ Update Status. 

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‘¨â€ğŸ’» Set up Python 3.9 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Clone the Repo ğŸ”
        uses: actions/checkout@master
        with:
          repository: ${{ secrets.REPO_NAME }}
      - name: âš™ï¸ Install dependencies.
        run: |
          pip install python-decouple pytz telethon
          pip install --upgrade pip
      - name: Run the UserClient. â–¶ï¸
        run: |
          python3 main.py
        env:
          APP_ID: ${{ secrets.APP_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOTS: ${{ secrets.BOTS }}
          SESSION: ${{ secrets.SESSION }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          MESSAGE_ID: ${{ secrets.MESSAGE_ID }}
